// fixtures/docs/*와 samples/manual.pdf의 바이너리(PDF/DOCX) 픽스처를 결정론으로 재생성한다.
// 실행: npm run fixtures — 산출물은 커밋된다, 이 스크립트는 내용을 바꿀 때만 다시 돌리면 된다.
// `npm run check`에는 포함되지 않는다. 전부 이 프로젝트가 직접 지은 가상의 내용이다(가드레일 4).
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { Document, HeadingLevel, Packer, Paragraph, TextRun } from "docx";
import PDFDocument from "pdfkit";

const DOCS_OUT = join(process.cwd(), "fixtures", "docs");
const SAMPLES_OUT = join(process.cwd(), "samples");
const FIXED_DATE = new Date("2026-09-06T00:00:00Z");

function pdf(
  outDir: string,
  file: string,
  build: (doc: PDFKit.PDFDocument) => void,
): Promise<void> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ info: { Title: file, CreationDate: FIXED_DATE, ModDate: FIXED_DATE } });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => {
      writeFileSync(join(outDir, file), Buffer.concat(chunks));
      resolve();
    });
    doc.on("error", reject);
    build(doc);
    doc.end();
  });
}

function heading(doc: PDFKit.PDFDocument, text: string): void {
  doc.font("Helvetica-Bold").fontSize(15).text(text);
  doc.moveDown(0.4);
}

function subheading(doc: PDFKit.PDFDocument, text: string): void {
  doc.font("Helvetica-Bold").fontSize(12).text(text);
  doc.moveDown(0.3);
}

function para(doc: PDFKit.PDFDocument, text: string): void {
  doc.font("Helvetica").fontSize(10).text(text, { align: "left" });
  doc.moveDown(0.8);
}

// 규정풍 조항(가상의 "내부 데이터 보관 정책") — CLAUDE.md 가드레일 4: 자체 제작.
// pdfPagesToText 휴리스틱(core/sections.ts)은 "줄바꿈된 문단의 마지막 줄이 페이지 최장 줄보다 뚜렷이
// 짧다"는 신호로 문단 끝을 찾는다. 문서가 짧으면 한 줄짜리 문단이 우연히 최장 줄의 70%를 넘어 이 신호가
// 흔들릴 수 있어, 모든 문단을 두 줄 이상으로 줄바꿈되게 충분히 길게 쓴다.
const ARTICLES: [string, string][] = [
  [
    "Article 1. Purpose",
    "This fictional policy sets out how the organization retains and disposes of operational data such as log files, support tickets, and configuration backups. It exists only as a test fixture for this project and describes no real organization or process.",
  ],
  [
    "Article 2. Scope",
    "This policy applies to log files, support tickets, and configuration backups generated by internal systems, regardless of which team owns the system. It does not apply to source code repositories or to data held by external processors.",
  ],
  [
    "Article 3. Retention Periods",
    "Log files are retained for ninety days from the date they are written. Support tickets are retained for two years after closure. Configuration backups are retained for one year from the date of the backup.",
  ],
  [
    "Article 4. Disposal",
    "Data past its retention period is deleted within thirty days by an automated job that runs on a nightly schedule. Deletion is logged with the record identifier and the deletion date, but never with the record's content.",
  ],
  [
    "Article 5. Exceptions",
    "Data subject to an active legal hold is retained until the hold is lifted, regardless of the periods set out in Article 3, and the hold itself is recorded together with the name of the requesting team.",
  ],
  [
    "Article 6. Review",
    "This policy is reviewed once every year by the team responsible for data governance. Each review records the reviewer, the review date, and a summary of any period that changed.",
  ],
];

async function buildRegulationPdf(): Promise<void> {
  await pdf(DOCS_OUT, "regulation.pdf", (doc) => {
    heading(doc, "Internal Data Retention Policy (Fixture)");
    para(
      doc,
      "This document is a fictional regulation-style fixture used only for this project's automated tests and describes no real organization, system, or policy.",
    );
    for (const [title, body] of ARTICLES) {
      subheading(doc, title);
      para(doc, body);
    }
  });
}

// 매뉴얼풍 — fixtures/docs/manual.md와 같은 가상의 "SkillSync X200"을 짧게 옮긴 PDF 버전.
async function buildManualPdf(): Promise<void> {
  await pdf(SAMPLES_OUT, "manual.pdf", (doc) => {
    heading(doc, "SkillSync X200 User Manual (Fixture)");
    para(
      doc,
      "The SkillSync X200 is a fictional bench-top controller used only as a sample for this project. Any resemblance to a real product is coincidental.",
    );
    subheading(doc, "Overview");
    para(
      doc,
      "The X200 reads sensor input over a serial bus and reports status through three LEDs: power, link, and fault.",
    );
    subheading(doc, "Installation");
    para(
      doc,
      "The X200 requires a host computer running the SkillSync Console, version 4 or later, and a free USB-C port capable of supplying 500 mA. Mount the unit on a flat, grounded surface.",
    );
    subheading(doc, "Configuration");
    para(
      doc,
      "Assign a static address in the 192.168.50.0/24 range from the Console's device list. Run the guided calibration wizard once per sensor; values are stored on the unit itself.",
    );
    subheading(doc, "Troubleshooting");
    para(
      doc,
      "If the link LED never turns solid, confirm the static address does not collide with another device on the same subnet, then hold the control button for five seconds to reboot.",
    );
  });
}

async function buildSampleDocx(): Promise<void> {
  const doc = new Document({
    creator: "live-skill fixtures",
    sections: [
      {
        children: [
          new Paragraph({ text: "New Hire Onboarding Checklist", heading: HeadingLevel.HEADING_1 }),
          new Paragraph({
            children: [
              new TextRun(
                "This fictional checklist is a test fixture only; it describes no real organization or process.",
              ),
            ],
          }),
          new Paragraph({ text: "Before Day One", heading: HeadingLevel.HEADING_2 }),
          new Paragraph({ text: "Provision the laptop and accounts.", bullet: { level: 0 } }),
          new Paragraph({ text: "Ship the welcome kit.", bullet: { level: 0 } }),
          new Paragraph({ text: "First Week", heading: HeadingLevel.HEADING_2 }),
          new Paragraph({ text: "Complete the security training module.", bullet: { level: 0 } }),
          new Paragraph({ text: "Meet with the assigned mentor.", bullet: { level: 0 } }),
          new Paragraph({ text: "Set up the local development environment.", bullet: { level: 0 } }),
        ],
      },
    ],
  });
  writeFileSync(join(DOCS_OUT, "sample.docx"), await Packer.toBuffer(doc));
}

// 예산 초과 테스트용 거대 문서 — 반복되지만 매번 조항 번호가 바뀌는, 완전히 지어낸 문장.
function buildOversizedMd(): void {
  const clause = (i: number): string =>
    `Clause ${String(i)}. The parties acknowledge that this fixture clause exists only to make ` +
    "the document large enough to exceed the compile token budget, and carries no real meaning.";
  const parts: string[] = ["# Oversized Fixture (Fixture)", "", "This document is synthetic and self-authored (guardrail 4)."];
  for (let i = 1; parts.join("\n").replace(/\s+/gu, "").length < 150_000; i++) {
    parts.push("", `## Clause ${String(i)}`, "", clause(i));
  }
  writeFileSync(join(DOCS_OUT, "oversized.md"), parts.join("\n"));
}

async function main(): Promise<void> {
  mkdirSync(DOCS_OUT, { recursive: true });
  mkdirSync(SAMPLES_OUT, { recursive: true });
  await buildRegulationPdf();
  await buildManualPdf();
  await buildSampleDocx();
  buildOversizedMd();
  console.log(`fixtures written to ${DOCS_OUT} and ${SAMPLES_OUT}`);
}

await main();
